- hosts: appdeploy
  gather_facts: false
  sudo: true
  tasks:
  - name: Deploy App
    copy: src=/var/lib/jenkins/workspace/tomcatdeploy/testapp.war dest="/usr/local/apache-tomcat-8.0.23/webapps/testapp##{{ buildnum }}.war" owner=tomcat group=tomcat
